export const SEARCH_LIST_TWEETS = 'SEARCH_LIST_TWEETS';
export const CLEAR_LIST_TWEETS = 'CLEAR_LIST_TWEETS';
export const SORT_TWEETS = 'SORT_TWEETS';
export const INSERT_TWEETS_FIELD_FILTER = 'INSERT_TWEETS_FIELD_FILTER';